ostreedev/ostree-rs

- .github/workflows/rust.yml
- src/.gitattributes
Mark src/auto/* as generated
---
ci: Fix buildroot to use new official image
Which is maintained and has updated rust.
---
>  ci: Fix buildroot to use new official image

- Cargo.toml
- src/lib.rs
This makes sure docs can be properly built when using the 'dox'
feature. It should fix auto-builds on docs.rs.
It also touches Cargo manifest in order to update stale URLs,
pointing to the auto-built docpages at docs.rs and sorting entries.
> lib: fix 'dox' feature

- Cargo.toml
Changes:
* cargoAdd 2021.3 feature
* cargo: fix version in features chain
* lib: fix 'dox' feature
* lib: re-export glib, gio
> ostree: release 0.12.1

- Cargo.toml
- sys/Cargo.toml
Ref: https://github.com/ostreedev/ostree-rs/pull/16#issuecomment-891131660
> cargo: bump ostree-sys to 0.8.1

- src/checksum.rs
- src/functions.rs
- src/lib.rs
- src/repo.rs
- src/se_policy.rs
And add basic docs for our manually implemented functions.
> Deny unused results, warn on missing docs (except auto/)

- src/core.rs
- src/lib.rs
- tests/core/mod.rs
- tests/tests.rs
This way it's more convenient for downstream crates like ostree-rs-ext
to convert loaded variants.
TODO: Can we add a feature for the `gvariant` crate and expose via
that too?
> Add new GLib 0.14 variant types for metadata types

- .github/workflows/rust.yml
- tests/sign/mod.rs
It's a huge trap for us not to build with the latest ostree feature
on, I didn't have my IDE configured for it, and CI didn't have
it on.
The previous bump to glib 0.14 broke the Sign code.
> Fix build with --features=v2021_3, use in CI by default

- .gitlab-ci.yml
- Cargo.toml
- src/checksum.rs
- src/functions.rs
- src/object_name.rs
- src/repo.rs
- src/repo_checkout_at_options/mod.rs
- src/repo_checkout_at_options/repo_checkout_filter.rs
- src/repo_transaction_stats.rs
- src/sysroot_write_deployments_opts.rs
- sys/Cargo.toml
In general only `-sys` crates should depend on other `-sys`
crates.  IOW for us, `ostree-sys` depends on `glib-sys`.
By using the re-export, we avoid needing to keep a version lock
between `glib` and `glib-sys` in our main crate.  And similar
is true of our higher level reverse dependencies (e.g. `ostree-rs-ext`).
Also weaken our dependency to `0.14` as that's clearer.
---
> Use glib-sys via re-exported `glib::ffi` (and similar for gio)

- Cargo.toml
- sys/Cargo.toml
```
Colin Walters (8):
Add 2021.3 feature
Re-export glib, gio
Deny unused results, warn on missing docs (except auto/)
Add new GLib 0.14 variant types for metadata types
Fix build with --features=v2021_3, use in CI by default
Add more documentation for --features=v2021_3
Use glib-sys via re-exported `glib::ffi` (and similar for gio)
```
> Release 0.12.2

- src/lib.rs
Matching how gtk-rs does it.  Right now rpm-ostree does depend
on interacting with `ostree-sys` via the cxxrs bits.
> lib: Export ffi too

- Cargo.toml
Not strictly required for this repo, but it has the new variant
bindings we want in ostree-rs-ext.
> Cargo.toml: Bump to glib 0.14.4

- conf/ostree.toml
- src/auto/se_policy.rs
It's safe to send between threads, and I want to do so
in ostree-rs-ext to send to a tokio worker thread.
> Make `SePolicy` have `Send`

- src/repo.rs
- tests/util/mod.rs
This gives auto-cancelling semantics on `Drop`, plus a nicer
`.commit()` method on the transaction.
Matches the currently private `_OstreeRepoAutoTransaction` in the C
library.
> repo: Add `auto_transaction` and `TransactionGuard`

- src/sysroot.rs
This splits the builder completion steps into separate actions for
creating/loading a sysroot.
It also introduces a roundtrip test over a freshly-created empty
sysroot.
> sysroot: support create and load actions on builder

- .github/workflows/rust.yml
- src/kernel_args.rs
- src/object_details.rs
- src/object_name.rs
- src/repo.rs
- src/sysroot.rs
- tests/functions/mod.rs
This adds two jobs in order to check minimum toolchain compatibility,
and for overall linting.
Before getting there, it also fixes all the existing clippy warnings and rustfmt
the whole project.
> ci: add jobs for MSRV checks and linting

- src/core.rs
- src/repo.rs
- tests/repo/mod.rs
The fact that the uid/gid/mode are big endian bit me when I was
trying to parse this "by hand" in ostree-rs-ext.
Let's add a footgun-free API for this.
(And yeah, we should probably do the same for the other variant types)
> repo: Add an API to read and parse directory metadata

- Cargo.toml
- src/lib.rs
- src/repo.rs
- tests/repo/mod.rs
- tests/util/mod.rs
I'm trying to make more use of `cap-std` in our stack, and
this will be a key enabling API.
Actually a notable side benefit of this is that we don't need
to teach the ostree C code itself to use `openat2`, we inherit
cap-std's setup.
All of the internal ostree code using the prior `openat()` should
continue to work.
I only did basic sanity checking of this; there may be bugs
in other APIs.
> Add a `cap-std-apis` feature with open/create

- src/repo.rs
- tests/repo/mod.rs
Followup to the previous PR.  I realized now with `io_lifetimes`
we can offer a safe `dfd_borrow()` that *borrows* the file descriptor
for the repository.  (In contrast to the current `.dfd()` that returns
the raw version)
Building on that, add another API that re-acquires a `Dir` instance.
(In the future in theory we could optimize this more by knowing
whether or not the repo was constructed via cap-std, and perhaps
in theory synthesize a `&Dir` reference, but I don't think we
need that now)
> repo: Add two more cap-std APIs

- src/constants.rs
- src/lib.rs
Today we hardcode `/bin/bash` in
https://github.com/coreos/coreos-assembler/blob/2088d24884771093101d95f915c921505128ef76/src/cmd-build#L405
But that breaks the concept of a bidirectional bridge between
container image and ostree commit because this little bit of
knowledge is encoded at the buildsystem side.
This metadata key is intended to be written into an ostree commit,
and then we will use it automatically in `container encapsulate`.
The "source of truth" for this key will hence be able live in the same
place that's generating the ostree commit.
The more "proper" place for this is probably alongside the other
constants in the libostree core C code.  But that's tedious and
slow to release.  And Rust is the future.  And we've been slowly
adding more "core ostree" functionality here.
> Add `COMMIT_META_CONTAINER_CMD` constant

- src/auto/gpg_verify_result.rs
This cherry picks just the changes from
https://github.com/ostreedev/ostree/pull/2537
We don't need to wait to respin a new ostree release just
for this.
> Fast-track fix for `ostree_gpg_verify_result_get_all()`

- src/repo.rs
- tests/repo/mod.rs
The underlying `ostree_repo_load_file()` API has the caller pass
`NULL` for output arguments it doesn't want.  This isn't sanely
bindable in Rust - what the generator does is always request
all values, but maps them all to `Option<T>`.
The main cases are where a user wants either metadata, or both
metadata and content.  This API gives just metadata; it's a
bit more efficient as we don't need to open the file, and doesn't
require the caller to `unwrap()`.
> repo: Add `query_file` API

- src/repo.rs
- tests/util/mod.rs
I want to write APIs that *require* the caller to have set up
an ostree transaction.  It's natural to require passing a guard
to do so.  But then we want an accessor for the repo.
> Add a `repo()` accessor to `TransactionGuard`
